// Adapted from rfdiosuao/three-axes-futures-toolkit (MIT), commit 3ceeb2a.
// Changes: TqSdk real contracts, completed candles only, no assumed equity.
import {completedSeries,measureDirection,closingQuote,barDate} from '../dist/structure.js';
import {contractName} from '../dist/contract-name.js';
import {sectorFor} from '../dist/sectors.js';
export const toolkitSource={url:'https://github.com/rfdiosuao/three-axes-futures-toolkit',commit:'3ceeb2ad1e7d40f3cd779867859130ac56e0de19',license:'MIT',mode:'独立参考筛选，不替代五简正式规则'};
export function atr14(rows){if(rows.length<15)return null;const tr=rows.slice(-14).map((b,i)=>{const prev=rows[rows.length-15+i].close;return Math.max(b.high-b.low,Math.abs(b.high-prev),Math.abs(b.low-prev))});return tr.reduce((a,b)=>a+b,0)/14;}
export function axesFor(q){const d=completedSeries(q),w=completedSeries(q,'W'),m=completedSeries(q,'M');const day=measureDirection(d),week=measureDirection(w);const ma=m.length>=10?m.slice(-10).reduce((s,b)=>s+b.close,0)/10:null;const monthly=ma===null?'unknown':m.at(-1).close>ma?'long':m.at(-1).close<ma?'short':'flat';const side=ma===null||day.ma10===null||week.ma10===null?'unknown':monthly==='long'&&day.state==='上行同侧'&&week.state==='上行同侧'?'long':monthly==='short'&&day.state==='下行同侧'&&week.state==='下行同侧'?'short':'flat';const atr=atr14(d),last=d.at(-1),prev=d.at(-2);const oi=last&&prev&&Number.isFinite(last.openInterest)&&Number.isFinite(prev.openInterest)?last.openInterest-prev.openInterest:null;return {symbol:q.symbol,name:contractName(q),sector:sectorFor(q),side,quoteTime:q.quoteTime||null,timeStatus:q.quality?.timeStatus||'unknown',asOf:last?barDate(last):null,close:closingQuote(q),atr14:atr,referenceStop:atr&&['long','short'].includes(side)?last.close+(side==='long'?-1:1)*1.5*atr:null,completedCounts:{day:d.length,week:w.length,month:m.length},priceOiQuadrant:!prev||oi===null?'未知':`${last.close>prev.close?'价升':last.close<prev.close?'价跌':'价平'}${oi>0?'增仓':oi<0?'减仓':'仓平'}`,lots:null,permission:false};}
export function sizeByRisk({equity,riskPct,exposurePct,entry,stop,multiplier}){const values=[equity,riskPct,exposurePct,entry,stop,multiplier];if(!values.every(x=>Number.isFinite(x)&&x>0)||riskPct>1||exposurePct>1||entry===stop)throw Error('需填写有效权益、风险比例、敞口比例、入场、止损和核实后的合约乘数');const risk=Math.floor(equity*riskPct/(Math.abs(entry-stop)*multiplier)),exposure=Math.floor(equity*exposurePct/(entry*multiplier));return {lots:Math.min(risk,exposure),riskCapLots:risk,exposureCapLots:exposure,permission:false,notice:'仅按手工输入计算，未读取账户或组合持仓，不含费用滑点，不是下单许可'};}
const n=x=>Number.isFinite(x)?x.toLocaleString('zh-CN',{maximumFractionDigits:2}):'未知';
export function buildAxesReport(snapshot,now=new Date()){
 const rows=(snapshot.quotes||[]).filter(q=>Number.isFinite(q.volume)&&Number.isFinite(q.openInterest)&&q.volume>10000&&q.openInterest>10000).map(axesFor);const counts=Object.fromEntries(['long','short','flat','unknown'].map(s=>[s,rows.filter(x=>x.side===s).length]));const ranking=rows.filter(r=>Number.isFinite(r.close.changePct)).sort((a,b)=>b.close.changePct-a.close.changePct);const names=side=>rows.filter(r=>r.side===side).map(r=>r.name).join('、')||'无';const dates=[...new Set(rows.map(r=>r.asOf).filter(Boolean))].sort();const recent=rows.filter(r=>r.asOf===dates.at(-1));const text=[`小木 · 三板斧参考日报`, `生成：${now.toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}（北京时间）`, `1. 盘面总览\n采集状态：${snapshot.status}；研究池 ${rows.length} 个，非全月份合约。完成日K日期 ${dates[0]||'未知'}—${dates.at(-1)||'未知'}。`, `2. 多空环境\n多头共振 ${counts.long}：${names('long')}\n空头共振 ${counts.short}：${names('short')}\n不共振 ${counts.flat}；历史不足 ${counts.unknown}。不是入场信号。`, `3. 价量仓\n${recent.slice(0,12).map(r=>r.name+' '+r.priceOiQuadrant).join('；')||'数据不足'}\n基于同一合约相邻完成日K收盘与持仓变化，未推断资金流向。`, `4. 收盘涨跌榜\n${ranking.slice(0,5).map(r=>r.name+' '+n(r.close.changePct)+'% ['+r.close.asOf+']').join('；')}\n${ranking.slice(-5).reverse().map(r=>r.name+' '+n(r.close.changePct)+'% ['+r.close.asOf+']').join('；')}\n各合约收盘日期可能不同，不混称同一交易日排名。`, `5. 账户与风控\n账户未接入，权益、持仓和可用手数未知。不沿用上游500万元模拟权益。ATR参考止损仅供研究，账户风险须人工复核。`, `6. 下一步核验\n复核周线环境、60日高低区域、反K触发、库存/基差/产业事件。共振不代替五道门，未检索到的新闻不编写。`, `7. 纪律\n结构先过关，再谈机会。保留反证；不自动下单，不生成交易许可。`, `8. 口径\n来源TqSdk，实际月份合约，量仓均＞1万手；周/月按完成日K保守聚合，首尾周期排除。ATR14基于前收，1.5倍仅为外部参考参数。\n方法来源：${toolkitSource.url}`].join('\n\n');return {generatedAt:now.toISOString(),source:toolkitSource,status:snapshot.status,counts,coverage:{subscribed:snapshot.liquidity?.total??0,retained:rows.length},rows,text,permission:false};}
