import WebSocket,{WebSocketServer} from 'ws';
import {randomBytes,randomUUID} from 'node:crypto';
import {pack,unpack,sessionParameters} from './volc-protocol.mjs';
import {assistantReply} from './assistant.mjs';
import {getReport} from './research-agent.mjs';
const tickets=new Map(),calls=new Set();let lastError=null;
const key=()=>process.env.VOLC_VOICE_API_KEY||process.env.VOLC_VOICE_ACCESS_TOKEN;
export function volcStatus(){return {configured:!!key(),provider:'volcengine',auth:'API Key',research:'DeepSeek',active:calls.size,lastError,notice:'火山语音收发，DeepSeek负责回答与研究；停止播报不会取消后台任务。'};}
export function voiceTicket(contextSymbol){if(!key())throw Error('请先在本机配置火山语音API Key');if(!process.env.DEEPSEEK_API_KEY)throw Error('请先配置DeepSeek研究模型');for(const [k,v] of tickets)if(v.expires<Date.now())tickets.delete(k);if(tickets.size>=4)throw Error('请稍后再连接');const token=randomBytes(32).toString('hex');tickets.set(token,{expires:Date.now()+30000,contextSymbol:typeof contextSymbol==='string'?contextSymbol.slice(0,80):''});return {token};}
export function takeTicket(token){const t=tickets.get(token);tickets.delete(token);return t?.expires>Date.now()?t:null;}
export function asrText(payload){return Array.isArray(payload?.results)?payload.results.map(x=>typeof x.text==='string'?x.text:'').join('').slice(0,4000):'';}
export function attachVolc(server,port){const wss=new WebSocketServer({noServer:true,maxPayload:65536});server.on('upgrade',(req,socket,head)=>{if(req.url!=='/ws/volc'||!['http://127.0.0.1:'+port,'http://localhost:'+port].includes(req.headers.origin)||!['127.0.0.1:'+port,'localhost:'+port].includes(req.headers.host)||calls.size>=1){socket.destroy();return}wss.handleUpgrade(req,socket,head,ws=>connect(ws))});return ()=>{for(const c of calls)c.close();wss.close()};}
function connect(browser){let upstream,sid=randomUUID(),ready=false,closed=false,epoch=0,spokenEpoch=-1,tts=false,audio=[],audioSize=0,text='',speaking=false,context='',queue=[],busy=false,history=[],lastTurn=0,questionId=null,spokenQuestion=null;const jobs=new Map(),announcements=[];
 const tell=(type,data={})=>{if(browser.readyState===WebSocket.OPEN&&browser.bufferedAmount<2*1024*1024)browser.send(JSON.stringify({type,...data}))};
 const send=(event,payload={},isAudio=false)=>{if(upstream?.readyState===WebSocket.OPEN)upstream.send(pack(event,payload,event===1?null:sid,isAudio))};
 const clear=()=>{epoch++;tts=false;spokenEpoch=-1;audio=[];audioSize=0;tell('interrupt')};
 const fail=message=>{lastError=message;tell('error',{message});close()};
 const initTimer=setTimeout(()=>fail('语音初始化超时'),5000),limit=setTimeout(()=>fail('本次通话已达15分钟，请重新接通；后台研究继续'),900000);let handshake;
 const close=()=>{if(closed)return;closed=true;clearTimeout(initTimer);clearTimeout(handshake);clearTimeout(limit);clearInterval(jobTimer);ready=false;if(upstream?.readyState===WebSocket.OPEN){send(102);upstream.close();const force=setTimeout(()=>upstream.terminate(),1500);force.unref()}else upstream?.terminate();browser.close();calls.delete(call)};
 const call={close};calls.add(call);
 function speak(content){if(!ready||closed||speaking||!lastTurn)return;spokenEpoch=epoch;spokenQuestion=questionId;send(500,{start:true,end:false,content:''});send(500,{start:false,end:false,content:content.slice(0,500)});send(500,{start:false,end:true,content:''});}
 async function work(){if(busy)return;busy=true;try{while(queue.length){const item=queue.shift();if(item.epoch!==epoch)continue;history.push({role:'user',content:item.text});tell('working');try{const r=await assistantReply(history.slice(-18),context);for(const j of r.jobs||[])jobs.set(j.id,j);history.push({role:'assistant',content:r.text.slice(0,5500)});history=history.slice(-20);tell('result',{text:r.text,jobs:r.jobs||[]});if(item.epoch===epoch&&!closed)speak(r.text.replace(/[#*`]/g,'').slice(0,420))}catch{tell('result',{text:'查询没有完成，请检查模型与数据连接。',jobs:[]});if(item.epoch===epoch)speak('查询没有完成，请在工作台检查模型与数据连接。')}}}finally{busy=false}}
 const jobTimer=setInterval(async()=>{if(closed)return;for(const [id,j] of jobs){try{const r=await getReport(id);if(!r||r.status==='running')continue;jobs.delete(id);const summary=`${j.name||'品种'}的研究${r.status==='completed'?'已完成':'已结束'}，请在工作台查看报告。`;tell('job_complete',{id,text:summary});announcements.push(summary)}catch{}}if(!busy&&!speaking&&!tts&&announcements.length&&Date.now()-lastTurn>1500)speak(announcements.shift())},3000);jobTimer.unref();
 browser.on('message',(data,binary)=>{if(closed)return;try{if(binary){if(ready){if(data.length%2||data.length>32000)throw Error('audio');if(upstream.bufferedAmount>262144)return fail('语音网络拥堵，请重新连接');send(200,data,true)}return}const m=JSON.parse(data.toString());if(m.type==='init'&&!upstream){const ticket=takeTicket(m.token);if(!ticket)return fail('语音连接凭证已过期，请重试');clearTimeout(initTimer);context=ticket.contextSymbol;upstream=new WebSocket('wss://openspeech.bytedance.com/api/v3/realtime/dialogue',{headers:{'X-Api-Key':key(),'X-Api-Resource-Id':'volc.speech.dialog','X-Api-Connect-Id':randomUUID()},handshakeTimeout:12000,maxPayload:8*1024*1024});handshake=setTimeout(()=>fail('火山语音会话握手超时'),20000);upstream.on('open',()=>send(1));upstream.on('unexpected-response',(_,r)=>{r.resume();fail(`火山语音鉴权或权限校验失败（HTTP ${r.statusCode}）`)});upstream.on('error',()=>{if(!closed)fail('火山语音连接失败，请检查网络或服务权限')});upstream.on('close',()=>{if(!closed)fail('火山语音连接已结束，可重新接通')});upstream.on('message',frame=>{if(closed)return;try{const e=unpack(frame);if(e.type===15||[51,153,599].includes(e.event))return fail('火山语音服务拒绝本次请求，请检查服务权限和参数');if(e.event===50){send(100,sessionParameters());return}if(e.event===150){clearTimeout(handshake);ready=true;lastError=null;tell('ready');return}
 if(e.event===450){questionId=e.payload.question_id;clear();speaking=true;text='';return}if(e.event===451){text=asrText(e.payload)||text;tell('partial',{text});return}if(e.event===459){speaking=false;lastTurn=Date.now();if(text.trim()){tell('user',{text});queue.push({text,epoch});queue=queue.slice(-3);void work()}text='';return}
 // Only external DeepSeek text-to-speech is audible. Native model guesses are dropped.
 if(e.event===350){tts=e.payload.tts_type==='chat_tts_text'&&spokenEpoch===epoch&&e.payload.question_id===spokenQuestion;audio=[];audioSize=0;return}if(e.audio&&tts){audioSize+=e.payload.length;if(audioSize>4*1024*1024)return fail('语音片段超出长度限制');audio.push(e.payload);return}if(e.event===351){if(tts&&spokenEpoch===epoch&&audio.length){tell('audio',{data:Buffer.concat(audio).toString('base64')});tell('speaking')}audio=[];audioSize=0;return}if(e.event===359){tts=false;tell('listening');return}
 }catch{fail('语音数据解析失败，请重新连接')}});return}if(m.type==='interrupt'){clear();return}if(m.type==='finish')close();}catch{fail('语音客户端消息无效')}});
 browser.on('close',close);browser.on('error',close);
}
