import test from 'node:test';import assert from 'node:assert/strict';
import {decisionEvidence,calculatePlanRisk,decisionProtocol} from '../integrations/decision-support.mjs';
const base={direction:'long',allowedDirection:'long',entry:100,stop:95,multiplier:10,riskBudgetYuan:520,costPerLot:2};
test('risk sizing includes costs, missing portfolio constraints cannot imply executable lots',()=>{const r=calculatePlanRisk(base);assert.equal(r.riskPerLotYuan,52);assert.equal(r.riskCapLots,10);assert.equal(r.lots,null);assert.equal(r.plannedLossYuan,null);assert.equal(r.permission,false)});
test('strict caps can reduce to zero and loss is distinct from notional',()=>{const r=calculatePlanRisk({...base,marginCapLots:8,liquidityCapLots:7,portfolioCapLots:3});assert.equal(r.lots,3);assert.equal(r.plannedLossYuan,156);assert.equal(r.notionalYuan,3000);assert.equal(calculatePlanRisk({...base,marginCapLots:8,liquidityCapLots:7,portfolioCapLots:0}).lots,0)});
test('opposite direction, invalid stops, missing budgets and costs fail closed',()=>{assert.throws(()=>calculatePlanRisk({...base,direction:'short'}));assert.throws(()=>calculatePlanRisk({...base,stop:101}));assert.throws(()=>calculatePlanRisk({...base,riskBudgetYuan:undefined}));assert.throws(()=>calculatePlanRisk({...base,costPerLot:undefined}));assert.throws(()=>calculatePlanRisk({...base,multiplier:NaN}))});
test('short risk uses stop above entry and no absolute-value loophole',()=>{assert.equal(calculatePlanRisk({...base,direction:'short',allowedDirection:'short',stop:105}).riskPerLotYuan,52);assert.throws(()=>calculatePlanRisk({...base,direction:'short',allowedDirection:'short'}))});
test('missing market evidence produces no invented entries or sizes',()=>{const r=decisionEvidence({symbol:'SHFE.cu2611',bars:[]},{status:'stale'});assert.equal(r.allowedDirection,null);assert.equal(r.decisionCard.entry,null);assert.equal(r.decisionCard.stop,null);assert.equal(r.decisionCard.lots,null);assert.equal(r.nakedK.last,null)});
test('protocol retains report audit and separates untested patterns from facts',async()=>{const text=await decisionProtocol();assert.match(text,/右上角只做多，右下角只做空/);assert.match(text,/纸面触发不等于真实成交/);assert.match(text,/不能用未来全日振幅/);assert.match(text,/等待五简拍板/)});
