import test from 'node:test';import assert from 'node:assert/strict';
import {createBindingService} from '../integrations/im-binding.mjs';
const turn=()=>new Promise(r=>setImmediate(r));
const result={client_id:'cli_test',client_secret:'test-secret-never-expose',user_info:{open_id:'ou_owner',tenant_brand:'feishu'}};
function fixture(){let resolve,options;const writes=[];let activations=0;const service=createBindingService({register:o=>{options=o;return new Promise(r=>resolve=r)},qr:async()=> 'data:image/png;base64,test',persist:async r=>writes.push(r),activate:async()=>activations++});return {service,writes,get options(){return options},finish:r=>resolve(r),activated:()=>activations};}
test('QR binding uses minimal bot scopes and never returns credentials',async()=>{const x=fixture(),s=await x.service.start();assert.equal(x.options.addons.preset,false);assert.equal(x.options.createOnly,true);assert.deepEqual(x.options.addons.scopes.tenant,['im:message:send_as_bot','im:message.p2p_msg:readonly']);x.options.onQRCodeReady({url:'https://open.feishu.cn/test',expireIn:600});await turn();assert.equal(x.service.status(s.id).status,'waiting');x.finish(result);await turn();assert.equal(x.writes[0].target,'ou_owner');assert.equal(x.activated(),1);assert.equal(x.service.status(s.id).status,'bound');assert.ok(!JSON.stringify(x.service.status(s.id)).includes(result.client_secret))});
test('cancelled or replaced registration cannot save credentials or activate',async()=>{const x=fixture(),s=await x.service.start();x.service.cancel(s.id);x.finish(result);await turn();assert.equal(x.writes.length,0);assert.equal(x.activated(),0);assert.equal(x.service.status('wrong').status,'expired')});
test('non-Feishu QR origin and missing identity fail closed',async()=>{const x=fixture(),s=await x.service.start();x.options.onQRCodeReady({url:'https://evil.example/test',expireIn:600});await turn();x.finish(result);await turn();assert.equal(x.service.status(s.id).status,'failed');assert.equal(x.writes.length,0);const y=fixture(),t=await y.service.start();y.finish({...result,user_info:{}});await turn();assert.equal(y.service.status(t.id).status,'failed');assert.equal(y.writes.length,0)});
test('replacement drops a late result from the previous QR request',async()=>{const resolvers=[];const writes=[];const service=createBindingService({register:()=>new Promise(r=>resolvers.push(r)),qr:async()=>'',persist:async r=>writes.push(r),activate:async()=>{}});const a=await service.start();const b=await service.start();resolvers[0](result);await turn();assert.equal(writes.length,0);resolvers[1](result);await turn();assert.equal(writes.length,1);assert.equal(service.status(a.id).status,'expired');assert.equal(service.status(b.id).status,'bound')});
