import test from 'node:test';import assert from 'node:assert/strict';
import {voiceProvider} from '../dist/voice-provider.js';
import {VolcVoice} from '../dist/volc-voice.js';
import {readFileSync} from 'node:fs';
const storage=value=>({value,getItem(){return this.value},setItem(_,v){this.value=v}});
test('old gpt, missing and invalid provider migrate once to volc; browser remains advanced backup',()=>{for(const old of ['gpt',null,'invalid','volc','browser']){const s=storage(old);assert.equal(voiceProvider(s),old==='browser'?'browser':'volc');assert.equal(s.value,voiceProvider(s))}});
function setup(){
 const contexts=[],tracks=[];
 class Node{constructor(context){this.context=context;this.gain={value:1};this.port={};this.connections=[];this.stopped=false}connect(n){this.connections.push(n);return n}disconnect(n){this.connections=n?this.connections.filter(x=>x!==n):[]}start(t){this.startAt=t}stop(){this.stopped=true}}
 class Context{constructor(){this.currentTime=0;this.state='running';this.destination={};this.sampleRate=48000;this.audioWorklet={addModule:async()=>{}};contexts.push(this)}resume(){return Promise.resolve()}close(){this.state='closed';return Promise.resolve()}createGain(){return new Node(this)}createMediaStreamSource(){return new Node(this)}createAnalyser(){const n=new Node(this);n.fftSize=1024;n.frequencyBinCount=512;n.getFloatTimeDomainData=a=>a.fill(.1);n.getByteFrequencyData=a=>a.fill(128);return n}decodeAudioData(){return Promise.resolve({duration:1})}createBufferSource(){return new Node(this)}}
 class WS{constructor(){this.readyState=1;this.bufferedAmount=0;this.messages=[]}send(x){this.messages.push(x)}close(){this.readyState=3}}
 const originals={};for(const k of ['AudioContext','AudioWorkletNode','WebSocket','navigator','location'])originals[k]=Object.getOwnPropertyDescriptor(globalThis,k);
 Object.defineProperties(globalThis,{AudioContext:{value:Context,configurable:true},AudioWorkletNode:{value:Node,configurable:true},WebSocket:{value:WS,configurable:true},location:{value:{protocol:'http:',host:'127.0.0.1:4318'},configurable:true},navigator:{value:{mediaDevices:{getUserMedia:async()=>{const t={enabled:true,stop(){this.stopped=true}};tracks.push(t);return{getTracks:()=>[t],getAudioTracks:()=>[t]}}}},configurable:true}});
 let resets=0,graph;const facts=[];const v=new VolcVoice({api:async path=>path.endsWith('status')?{configured:true}:{token:'test'},status:()=>{},message:()=>{},onAudioGraph:x=>graph=x,onVoiceState:x=>facts.push(x),onOutputReset:()=>resets++});
 return{v,contexts,tracks,facts,get graph(){return graph},get resets(){return resets},cleanup(){v.stop();for(const[k,d]of Object.entries(originals))d?Object.defineProperty(globalThis,k,d):delete globalThis[k]}};
}
test('one context and microphone per call; 10 connect/hangup cycles release all owned resources',async()=>{const f=setup();try{for(let i=0;i<10;i++){await f.v.connect();f.v.event({type:'ready'},f.v.generation);assert.ok(f.graph.inputTap&&f.graph.outputTap);assert.equal(f.v.source.connections.filter(n=>n===f.v.inputTap.analyser).length,1);assert.ok(!f.v.source.connections.includes(f.v.audio.destination));f.v.stop();assert.deepEqual(f.graph,{});assert.equal(f.v.sources.size,0);assert.equal(f.v.facts.connection,'idle')}assert.equal(f.contexts.length,10);assert.equal(f.tracks.length,10);assert.ok(f.contexts.every(x=>x.state==='closed'));assert.ok(f.tracks.every(x=>x.stopped))}finally{f.cleanup()}});
test('queued audio is not speaking; muting input preserves active playback; interrupt clears output only',async()=>{const f=setup();try{await f.v.connect();f.v.event({type:'ready'},f.v.generation);f.v.event({type:'audio',data:'AAAA'},f.v.generation);await f.v.chain;f.v.syncPlayback();assert.equal(f.v.facts.agentSpeaking,false);f.v.audio.currentTime=.1;f.v.syncPlayback();assert.equal(f.v.facts.agentSpeaking,true);const src=[...f.v.sources][0];assert.deepEqual(src.connections,[f.v.playbackGain]);f.v.mute(true);assert.equal(f.v.facts.micMuted,true);assert.equal(f.v.facts.agentSpeaking,true);assert.equal(src.stopped,false);assert.equal(f.tracks[0].enabled,false);f.v.interrupt();assert.equal(src.stopped,true);assert.equal(f.v.facts.agentSpeaking,false);assert.equal(f.v.intervals.size,0);assert.ok(!f.v.inputTap.disposed);assert.ok(f.resets>0)}finally{f.cleanup()}});
test('late decode after interrupt or hangup cannot schedule or revive old audio',async()=>{const f=setup();try{await f.v.connect();f.v.event({type:'ready'},f.v.generation);for(const action of ['interrupt','stop']){let finish;f.v.audio.decodeAudioData=()=>new Promise(r=>finish=r);f.v.event({type:'audio',data:'AAAA'},f.v.generation);const pending=f.v.chain;await Promise.resolve();f.v[action]();finish({duration:1});await pending;assert.equal(f.v.sources.size,0);assert.equal(f.v.facts.agentSpeaking,false)}}finally{f.cleanup()}});
test('permission denial clears context and preserves useful error state',async()=>{const f=setup();try{navigator.mediaDevices.getUserMedia=async()=>{throw Object.assign(Error('denied'),{name:'NotAllowedError'})};await f.v.connect();assert.equal(f.v.facts.connection,'error');assert.ok(f.contexts.every(x=>x.state==='closed'));assert.equal(f.v.ready,false)}finally{f.cleanup()}});
test('structured working facts allow input and never cancel research on hangup',async()=>{const f=setup();try{await f.v.connect();f.v.event({type:'ready'},f.v.generation);f.v.event({type:'working'},f.v.generation);f.v.event({type:'partial',text:'继续研究'},f.v.generation);assert.equal(f.v.facts.working,true);assert.equal(f.v.facts.userSpeaking,true);const ws=f.v.ws;f.v.stop();assert.deepEqual(ws.messages.map(s=>JSON.parse(s).type),['finish'])}finally{f.cleanup()}});
test('desktop retains isolation and build copies minimal preload',()=>{const main=readFileSync('desktop/main.cjs','utf8');for(const flag of ['nodeIntegration:false','contextIsolation:true','sandbox:true','webSecurity:true',"titleBarStyle:'hiddenInset'"])assert.ok(main.includes(flag));assert.match(readFileSync('scripts/build-desktop.mjs','utf8'),/copyFile\('desktop\/preload.cjs'/);assert.doesNotMatch(readFileSync('desktop/preload.cjs','utf8'),/ipcRenderer|contextBridge/)});
test('hanging permission prompt cannot spawn duplicate microphone requests; late stream is stopped',async()=>{const f=setup();try{let release,calls=0;const t={stop(){this.stopped=true}};navigator.mediaDevices.getUserMedia=()=>{calls++;return new Promise(r=>release=r)};const pending=f.v.connect();for(let i=0;i<5&&!release;i++)await Promise.resolve();assert.ok(release);f.v.stop();await f.v.connect();assert.equal(calls,1);release({getTracks:()=>[t]});await pending;assert.equal(t.stopped,true);assert.equal(f.v.pendingMic,null)}finally{f.cleanup()}});
