import test from 'node:test';import assert from 'node:assert/strict';
import {pack,unpack,sessionParameters} from '../integrations/volc-protocol.mjs';
import {asrText,takeTicket,voiceTicket} from '../integrations/volc-voice.mjs';
test('Volc binary protocol decodes compressed JSON and exact audio bytes',()=>{const b=pack(451,{results:[{text:'沪铜'}]},'session');b[1]=0x94;assert.equal(asrText(unpack(b).payload),'沪铜');const audio=Buffer.from([0,1,2,3]),a=pack(352,audio,'session',true);a[1]=0xb4;assert.deepEqual(unpack(a).payload,audio);assert.throws(()=>unpack(b.subarray(0,-1)));assert.throws(()=>unpack(Buffer.alloc(3)))});
test('browser voice ticket is single use and never contains provider credentials',()=>{const oldKey=process.env.VOLC_VOICE_API_KEY,oldModel=process.env.DEEPSEEK_API_KEY;process.env.VOLC_VOICE_API_KEY='unit-test-key';process.env.DEEPSEEK_API_KEY='unit-test-model';try{const t=voiceTicket('SHFE.cu2610');assert.deepEqual(Object.keys(t),['token']);assert.equal(takeTicket(t.token).contextSymbol,'SHFE.cu2610');assert.equal(takeTicket(t.token),null);assert.equal(takeTicket('unknown'),null)}finally{for(const [k,v] of [['VOLC_VOICE_API_KEY',oldKey],['DEEPSEEK_API_KEY',oldModel]])if(v===undefined)delete process.env[k];else process.env[k]=v}});
test('ASR parser ignores provider metadata and bounds transcript',()=>{assert.equal(asrText({extra:{secret:'not output'},results:[{text:'研究'},{text:'沪铜'}]}),'研究沪铜');assert.equal(asrText(null),'');assert.equal(asrText({results:[{text:'x'.repeat(5000)}]}).length,4000);assert.equal(sessionParameters().dialog.extra.input_mod,'audio')});

import vm from 'node:vm';import {readFileSync} from 'node:fs';
test('microphone resampler retains timing across 128-frame blocks',()=>{for(const rate of [48000,44100]){let Processor,count=0;vm.runInNewContext(readFileSync(new URL('../dist/volc-capture.js',import.meta.url),'utf8'),{sampleRate:rate,AudioWorkletProcessor:class{constructor(){this.port={postMessage:b=>count+=b.byteLength/2}}},registerProcessor:(_,p)=>Processor=p});const p=new Processor();for(let n=0;n<rate;n+=128)p.process([[new Float32Array(Math.min(128,rate-n)).fill(.25)]]);assert.ok(Math.abs(count+p.used-16000)<=1,`${rate}: ${count+p.used}`)}});
